spring.application.name=usp
server.port=8991
app.base-url=http://127.0.0.1:8991

# base directory for log files - actual logs go to <app.log.base-path>/<spring.application.name>/<yyyy-MM-dd>/app.log
app.log.base-path=/var/log
# controls what gets written to the log file (and console) - e.g. TRACE, DEBUG, INFO, WARN, ERROR
logging.level.root=INFO
logging.level.org.arsalanansari.usp=INFO
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.h2.console.enabled=true
spring.h2.console.path=/h2Console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.client-type=lettuce
spring.data.redis.lettuce.pool.max-active=100
spring.data.redis.lettuce.pool.max-idle=50
spring.data.redis.lettuce.pool.min-idle=10
spring.data.redis.lettuce.pool.max-wait=2000ms
spring.data.redis.timeout=5000ms